# Generated by Django 3.2.9 on 2021-12-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualiza', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('date', 'currency'), name='unique_currency_by_date'),
        ),
    ]
